// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int i=0;
		int count=0;
		double x;
		while (i<N) {
			x= Math.random();
			if(x<0.5){
				count++;
			}
			i++;
		}
		System.out.println("x < 0.5: " + count + " times");
		System.out.println("x >= 0.5: " +  (N-count) + " times");
		if(count>0 && count!=N){
			System.out.println("Ratio:" + ((double)(N-count)/count));
		}
	}
}
